title: TreeHouse
author: Yingshuang Fan
logo: logo.webp
execute:
  execute_notebooks: auto
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: true

bibtex_bibfiles:
  - ./references.bib

html:
  favicon: "logo.webp"  # A path to a favicon image

launch_buttons:
  notebook_interface: jupyterlab
  colab_url: "https://colab.research.google.com"

repository:
  url: https://github.com/yingshuangfan/treehouse
  path_to_book: ""
  branch: master

parse:
  myst_enable_extensions: # https://myst-parser.readthedocs.io/en/latest/syntax/optional.html
    - amsmath
    - dollarmath
