# In _config.yml
title: TreeHouse
author: Yingshuang Fan
logo: logo.webp
execute:
  execute_notebooks: auto
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: true

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ./references.bib

launch_buttons:
  notebook_interface: jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  # binderhub_url: https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  # jupyterhub_url: ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  # thebe: false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url: "https://colab.research.google.com" # The URL of Google Colab (https://colab.research.google.com)

repository:
  url                       : https://github.com/yingshuangfan/treehouse  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links
